// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Category {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "name": string;
    "color": string;

    /** Creates a new Category instance. */
    constructor($$source: Partial<Category> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     */
    static createFrom($$source: any = {}): Category {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category($$parsedSource as Partial<Category>);
    }
}

export enum ContentType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContentTypePlain = "text/plain",
    ContentTypeMarkdown = "text/markdown",
    ContentTypeHTML = "text/html",
};

export class Note {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "title": string;
    "content": string;
    "color": string;
    "zoom_multiplier": number;
    "text_color": string;
    "content_type": ContentType;
    "category_id": number | null;
    "category": Category | null;
    "window_state": WindowState | null;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("zoom_multiplier" in $$source)) {
            this["zoom_multiplier"] = 0;
        }
        if (!("text_color" in $$source)) {
            this["text_color"] = "";
        }
        if (!("content_type" in $$source)) {
            this["content_type"] = ContentType.$zero;
        }
        if (!("category_id" in $$source)) {
            this["category_id"] = null;
        }
        if (!("category" in $$source)) {
            this["category"] = null;
        }
        if (!("window_state" in $$source)) {
            this["window_state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("category" in $$parsedSource) {
            $$parsedSource["category"] = $$createField11_0($$parsedSource["category"]);
        }
        if ("window_state" in $$parsedSource) {
            $$parsedSource["window_state"] = $$createField12_0($$parsedSource["window_state"]);
        }
        return new Note($$parsedSource as Partial<Note>);
    }
}

export class WindowState {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "note_id": number | null;
    "width": number;
    "height": number;
    "x": number;
    "y": number;
    "pinned": boolean;
    "visible": boolean;

    /** Creates a new WindowState instance. */
    constructor($$source: Partial<WindowState> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("note_id" in $$source)) {
            this["note_id"] = null;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowState instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowState($$parsedSource as Partial<WindowState>);
    }
}

// Private type creation functions
const $$createType0 = Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = WindowState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
