// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DetailedVersionInfo {
    "version": string;
    "commit": string;
    "buildDate": string;

    /** Creates a new DetailedVersionInfo instance. */
    constructor($$source: Partial<DetailedVersionInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("buildDate" in $$source)) {
            this["buildDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetailedVersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DetailedVersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetailedVersionInfo($$parsedSource as Partial<DetailedVersionInfo>);
    }
}
