// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateCategory(name: string, color: string): $CancellablePromise<models$0.Category | null> {
    return $Call.ByID(3699248769, name, color).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateNote(title: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(4255321037, title, content);
}

export function CreateNoteInCategory(categoryID: number, color: string): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(367115934, categoryID, color).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DeleteCategory(id: number): $CancellablePromise<void> {
    return $Call.ByID(3907711498, id);
}

export function DeleteNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(2806301726, id);
}

export function RetrieveCategories(): $CancellablePromise<models$0.Category[]> {
    return $Call.ByID(3010397633).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RetrieveCategory(id: number): $CancellablePromise<models$0.Category | null> {
    return $Call.ByID(1087751181, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RetrieveNote(id: number): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(3973604553, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RetrieveNotesByCategory(categoryID: number): $CancellablePromise<models$0.Note[]> {
    return $Call.ByID(3167182683, categoryID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function UpdateCategory(category: models$0.Category | null): $CancellablePromise<void> {
    return $Call.ByID(1713387460, category);
}

export function UpdateNote(note: models$0.Note | null): $CancellablePromise<void> {
    return $Call.ByID(2274292440, note);
}

// Private type creation functions
const $$createType0 = models$0.Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.Note.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Array($$createType2);
