// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateNote(title: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(4255321037, title, content);
}

export function RetrieveNote(id: number): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(3973604553, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateNote(note: models$0.Note | null): $CancellablePromise<void> {
    return $Call.ByID(2274292440, note);
}

// Private type creation functions
const $$createType0 = models$0.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
