// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

export function CreateWindowForNote(note: models$0.Note): $CancellablePromise<application$0.WebviewWindow | null> {
    return $Call.ByID(740223165, note).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetNoteIDByWindow(window: application$0.WebviewWindow | null): $CancellablePromise<[number, boolean]> {
    return $Call.ByID(980400530, window);
}

export function GetWindowByNoteID(noteID: number): $CancellablePromise<[application$0.WebviewWindow | null, boolean]> {
    return $Call.ByID(2760519386, noteID).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    });
}

export function HandleWindowAction(action: string, noteID: number): $CancellablePromise<void> {
    return $Call.ByID(1305976718, action, noteID);
}

export function RegisterEventHandlers(): $CancellablePromise<void> {
    return $Call.ByID(4053000472);
}

// Private type creation functions
const $$createType0 = application$0.WebviewWindow.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
